// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPy40caYk3rp6hQnAdLBORtXXQaVE2Qpo',
    appId: '1:242338274978:web:c9f9317ec5a2ca3d7bc1fb',
    messagingSenderId: '242338274978',
    projectId: 'start-quiz-e97a0',
    authDomain: 'start-quiz-e97a0.firebaseapp.com',
    storageBucket: 'start-quiz-e97a0.appspot.com',
    measurementId: 'G-72B4MLQNY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdel2dPLAyIeZbR2dZvjPfequ86RDJYQc',
    appId: '1:242338274978:android:85c329e2027cb7d67bc1fb',
    messagingSenderId: '242338274978',
    projectId: 'start-quiz-e97a0',
    storageBucket: 'start-quiz-e97a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3rI799pf4I8CSu9oT42Wvcx7W7MZ_pmM',
    appId: '1:242338274978:ios:62321844f1ea920f7bc1fb',
    messagingSenderId: '242338274978',
    projectId: 'start-quiz-e97a0',
    storageBucket: 'start-quiz-e97a0.appspot.com',
    iosBundleId: 'com.example.quizle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3rI799pf4I8CSu9oT42Wvcx7W7MZ_pmM',
    appId: '1:242338274978:ios:3c6bef4cd8e84deb7bc1fb',
    messagingSenderId: '242338274978',
    projectId: 'start-quiz-e97a0',
    storageBucket: 'start-quiz-e97a0.appspot.com',
    iosBundleId: 'com.example.quizle.RunnerTests',
  );
}
